import streamlit as st
import requests
import datetime
import sys

BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title="✈ Travel Planning Agent",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state= "expanded"
)

st.title("✈ Travel Planning Agent")

if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I help you in planning a trip? Let me know where do you want to visit.")


with st.form(key="query_form", clear_on_submit=True):
    submit_button = st.form_submit_button("Send")
    user_input = st.text_input("User Input", placeholder= "e.g: Plan a trip to Goa for 4 days")

if submit_button and user_input.strip():
    try:
        with st.spinner("Making Your Custom plan..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json= payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned")
            markdown_content = f"""# ✈ AI Travel Plan
            # **Generated:** {datetime.datetime.now().strftime("%Y-%m-%d at %H:%M:%S")}
            # **Created By:** Travel Agent

            ---
            {answer}
            ---

            *This travel plan was generated by ai. Please verify all information, especially prices, operational expenses
            """

            st.markdown(markdown_content)
        else:
            st.error("Agent Failed to respond: " + response.text)

    except Exception as e:
        raise f"The response failed due to {e}"